INSERT INTO tb_category (name,created_at) values ('Books',NOW())
INSERT INTO tb_category (name,created_at) values ('Eletronics',NOW())
INSERT INTO tb_category (name,created_at) values ('Kitchen',NOW())INSERT INTO tb_category (name,created_at) values ('Books',NOW())
INSERT INTO tb_category (name,created_at) values ('ALCA',NOW())
INSERT INTO tb_category (name,created_at) values ('CITY',NOW())INSERT INTO tb_category (name,created_at) values ('Books',NOW())
INSERT INTO tb_category (name,created_at) values ('BAYERN',NOW())
INSERT INTO tb_category (name,created_at) values ('ZEZ',NOW())